#! /bin/sh
# kcminputrc Mouse cursorTheme 'Oxygen_White'
kcminputrc_mouse_cursortheme=Oxygen_White
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=24
# ksplashrc KSplash Theme Default
ksplashrc_ksplash_theme=Default
# ksplashrc KSplash Engine KSplashX
ksplashrc_ksplash_engine=KSplashX
# krandrrc Display ApplyOnStartup false
krandrrc_display_applyonstartup=true
# krandrrc Display StartupCommands ''
krandrrc_display_startupcommands='xrandr --output LVDS1 --pos 0x0 --mode 1366x768 --refresh 60.0006
xrandr --output VGA1 --pos 0x768 --mode 1920x1080 --refresh 60
xrandr --noprimary'
# krandrrc [Screen0]
# krandrrc [Screen1]
# krandrrc [Screen2]
# krandrrc [Screen3]
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=0
# kdeglobals Locale Language '' # trigger requesting languages from KLocale
kdeglobals_locale_language=''
klocale_languages=zh_CN:en_US
